script: "rake test:travis"
rvm:
  - 1.9.2
  - 1.9.3

notifications:
  email:
    - yorickpeterse@gmail.com

branches:
  only:
    - develop
    - master

env:
  - 'ADAPTER=sqlite DATABASE=database.db'
  - 'ADAPTER=mysql2 DATABASE=zen_dev'
  - 'ADAPTER=postgres DATABASE=zen_dev USERNAME=postgres'
  - 'LRU=1 ADAPTER=sqlite DATABASE=database_lru.db'
  - 'LRU=1 ADAPTER=mysql2 DATABASE=zen_dev_lru'
  - 'LRU=1 ADAPTER=postgres DATABASE=zen_dev_lru USERNAME=postgres'

before_script:
  - "mysql -e 'CREATE DATABASE zen_dev_1_9_2;'"
  - "mysql -e 'CREATE DATABASE zen_dev_1_9_3;'"
  - "mysql -e 'CREATE DATABASE zen_dev_lru_1_9_2;'"
  - "mysql -e 'CREATE DATABASE zen_dev_lru_1_9_3;'"
  - "psql -c 'CREATE DATABASE zen_dev_1_9_2;' -U postgres"
  - "psql -c 'CREATE DATABASE zen_dev_lru_1_9_2;' -U postgres"
  - "psql -c 'CREATE DATABASE zen_dev_1_9_3;' -U postgres"
  - "psql -c 'CREATE DATABASE zen_dev_lru_1_9_3;' -U postgres"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
