script: "rake setup; rake test:default"
rvm:
  - 1.9.2
  - 1.9.3

notifications:
  email:
    - yorickpeterse@gmail.com

branches:
  only:
    - develop
    - master

env:
  - 'ADAPTER=sqlite'
  - 'ADAPTER=mysql2 DATABASE=zen_dev'
  - 'ADAPTER=postgres DATABASE=zen_dev USERNAME=postgres'
  - 'LRU=1 ADAPTER=sqlite DATABASE=database_1.db'
  - 'LRU=1 ADAPTER=mysql2 DATABASE=zen_dev_1'
  - 'LRU=1 ADAPTER=postgres DATABASE=zen_dev_1 USERNAME=postgres'

before_script:
  - "mysql -e 'CREATE DATABASE zen_dev;'"
  - "mysql -e 'CREATE DATABASE zen_dev_1;'"
  - "psql -c  'CREATE DATABASE zen_dev;' -U postgres"
  - "psql -c  'CREATE DATABASE zen_dev_1;' -U postgres"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
