require __DIR__('categories/lib/categories')
require __DIR__('comments/lib/comments')
require __DIR__('custom_fields/lib/custom_fields')
require __DIR__('menus/lib/menus')
require __DIR__('sections/lib/sections')
require __DIR__('settings/lib/settings')
require __DIR__('users/lib/users')
