module Zen
  Zen::RakeTask = true
end

require File.expand_path('../helper', __FILE__)

import __DIR__('../lib/zen/task/db.rake')
import __DIR__('../lib/zen/task/package.rake')

namespace :db do
  desc 'Creates the user for all the tests'
  task :test_user do
    # Create a default user and group
    group = Users::Model::UserGroup.create(
      :name        => 'Administrators',
      :slug        => 'administrators',
      :super_group => true
    )

    user = Users::Model::User.create(
      :email    => 'spec@domain.tld',
      :name     => 'Spec',
      :password => 'spec'
    )

    user.activate!

    user.user_group_pks = [group.id]
  end
end
