require File.expand_path('../helper', __FILE__)
require __DIR__('../lib/zen/task/db')
require __DIR__('../lib/zen/task/package')
require __DIR__('../lib/zen/task/tool')

##
# Extend the DB namespace with an extra task.
#
# @author Yorick Peterse
# @since  0.2.5
#
namespace :db do

  desc 'Creates a user used for running all specifications'
  task :test_user do
    # Create a default user and group
    group = Users::Model::UserGroup.new(
      :name => 'Administrators',
      :slug => 'administrators', :super_group => true
    ).save

    user = Users::Model::User.new(
      :email    => 'spec@domain.tld', :name   => 'Spec',
      :password => 'spec'           , :status => 'open'
    ).save

    user.user_group_pks = [group.id]
  end

end
