require File.expand_path('../app.rb', __FILE__)

# Load all core tasks
import 'zen/task/db.rake'
import 'zen/task/package.rake'
import 'zen/task/proto.rake'
import 'zen/task/theme.rake'
import 'zen/task/plugin.rake'

task_dir = File.expand_path('../task', __FILE__)

# Load all tasks from ./task if the directory exists
if File.directory?(task_dir)
  Dir.glob("#{task_dir}/**/*.rake").each do |task|
    import task
  end
end

