require 'fileutils'

module Zen
  module Task
    ##
    # The Clean task can be used to remove various files from the repository.
    #
    # @author Yorick Peterse
    # @since  0.2
    #
    class Clean < Thor
      include Thor::Actions

      namespace :clean

      ##
      # Removes all log files from the spec directory.
      #
      # @author Yorick Peterse
      # @since  0.2
      #
      desc 'log', 'Removes all log files from the spec directory'
      def log
        zen_path = File.expand_path('../../../../', __FILE__)

        log_files = Dir.glob("#{zen_path}/spec/log/**/*.log")
        log_files.each { |file| File.unlink(file) }
      end

      ##
      # Removes all files generated by YARD.
      #
      # @author Yorick Peterse
      # @since  0.2
      #
      desc 'yard', 'Removes all files generated by YARD'
      def yard
        zen_path = File.expand_path('../../../../', __FILE__)

        FileUtils.rm_rf("#{zen_path}/doc")
        FileUtils.rm_rf("#{zen_path}/.yardoc")
      end

    end
  end
end
